/*
 * Hikage - A real-time Android View runtime powered by Kotlin DSL.
 * Copyright (C) 2019 HighCapable
 * https://github.com/BetterAndroid/Hikage
 *
 * Apache License Version 2.0
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * This file is created by fankes on 2026/5/31.
 */
@file:Suppress("unused", "FunctionName", "UNCHECKED_CAST")
@file:JvmName("HikagePerformerUtils")

package com.highcapable.hikage.core.layout

import android.view.View
import android.view.ViewGroup
import androidx.annotation.LayoutRes
import androidx.viewbinding.ViewBinding
import com.highcapable.betterandroid.ui.extension.binding.ViewBinding
import com.highcapable.betterandroid.ui.extension.binding.ViewBindingBuilder
import com.highcapable.betterandroid.ui.extension.view.ViewLayoutParams
import com.highcapable.hikage.annotation.Hikageable
import com.highcapable.hikage.core.Hikage
import com.highcapable.hikage.core.attrs.HikageAttribute
import com.highcapable.hikage.core.base.HikagePerformer
import com.highcapable.hikage.core.base.HikageView
import com.highcapable.hikage.core.base.ViewConstructor
import com.highcapable.hikage.core.layout.exception.PerformerException
import kotlin.reflect.KClass

/**
 * Provide a new [View] instance [V].
 * @param viewClass the view class.
 * @param factory the view factory, used to create the view instance.
 * @param lparams the view layout params.
 * @param id the view id, generated by default.
 * @param attrs the attributes body.
 * @param init the view initialization body.
 * @return [V]
 */
@Hikageable
fun <V : View, LP : ViewGroup.LayoutParams> Hikage.Performer<LP>.View(
    viewClass: KClass<V>,
    factory: ViewConstructor<V>? = null,
    lparams: LayoutParams? = null,
    id: String? = null,
    attrs: HikageAttribute = {},
    init: HikageView<V> = {}
) = resolveContext().View(viewClass, factory, lparams, id, attrs, init)

/**
 * Provide a new [View] instance.
 * @param factory the view factory, used to create the view instance.
 * @param lparams the view layout params.
 * @param id the view id, generated by default.
 * @param attrs the attributes body.
 * @param init the view initialization body.
 * @return [View]
 */
@Hikageable
fun <LP : ViewGroup.LayoutParams> Hikage.Performer<LP>.View(
    factory: ViewConstructor<View>? = null,
    lparams: LayoutParams? = null,
    id: String? = null,
    attrs: HikageAttribute = {},
    init: HikageView<View> = {}
) = resolveContext().View(lparams, factory, id, attrs, init)

/**
 * Provide a new [ViewGroup] instance [VG].
 *
 * Provide the new type of [ViewGroup.LayoutParams] down via [LP].
 *
 * - Note: The [VG] must be inherited from [ViewGroup].
 * @param viewClass the view class.
 * @param childLpClass the child layout params class.
 * @param factory the view factory, used to create the view instance.
 * @param lparams the view layout params.
 * @param id the view id, generated by default.
 * @param attrs the attributes body.
 * @param init the view initialization body.
 * @param performer the performer body.
 * @return [VG]
 */
@Hikageable
fun <VG : ViewGroup, NLP : ViewGroup.LayoutParams, LP : ViewGroup.LayoutParams> Hikage.Performer<LP>.ViewGroup(
    viewClass: KClass<VG>,
    childLpClass: KClass<NLP>,
    factory: ViewConstructor<VG>? = null,
    lparams: LayoutParams? = null,
    id: String? = null,
    attrs: HikageAttribute = {},
    init: HikageView<VG> = {},
    performer: HikagePerformer<NLP> = {}
) = resolveContext().ViewGroup(viewClass, childLpClass, factory, lparams, id, attrs, init, performer)

/**
 * Provide a new [ViewGroup] instance [VG].
 *
 * - Note: The [VG] must be inherited from [ViewGroup].
 * @param viewClass the view class.
 * @param factory the view factory, used to create the view instance.
 * @param lparams the view layout params.
 * @param id the view id, generated by default.
 * @param attrs the attributes body.
 * @param init the view initialization body.
 * @param performer the performer body.
 * @return [VG]
 */
@Hikageable
fun <VG : ViewGroup, LP : ViewGroup.LayoutParams> Hikage.Performer<LP>.ViewGroup(
    viewClass: KClass<VG>,
    factory: ViewConstructor<VG>? = null,
    lparams: LayoutParams? = null,
    id: String? = null,
    attrs: HikageAttribute = {},
    init: HikageView<VG> = {},
    performer: HikagePerformer<ViewGroup.LayoutParams> = {}
) = resolveContext().ViewGroup(viewClass, factory, lparams, id, attrs, init, performer)

/**
 * Provide layout from [resId].
 * @param resId the layout resource id.
 * @param lparams the view layout params.
 * @param id the view id, generated by default.
 * @return [View]
 */
@Hikageable
fun <LP : ViewGroup.LayoutParams> Hikage.Performer<LP>.Layout(
    @LayoutRes resId: Int,
    lparams: LayoutParams? = null,
    id: String? = null
) = resolveContext().Layout(resId, lparams, id)

/**
 * Provide layout from [ViewBinding].
 * @param bindingBuilder the view binding builder.
 * @param lparams the view layout params.
 * @param id the view id, generated by default.
 * @return [VB]
 */
@Hikageable
fun <VB : ViewBinding, LP : ViewGroup.LayoutParams> Hikage.Performer<LP>.Layout(
    bindingBuilder: ViewBindingBuilder<VB>,
    lparams: LayoutParams? = null,
    id: String? = null
) = resolveContext().Layout(bindingBuilder, lparams, id)

/**
 * Provide layout from exists [View].
 * @param view the view instance.
 * @param lparams the view layout params.
 * @param id the view id, generated by default.
 * @return [View]
 */
@Hikageable
fun <LP : ViewGroup.LayoutParams> Hikage.Performer<LP>.Layout(
    view: View,
    lparams: LayoutParams? = null,
    id: String? = null
) = resolveContext().Layout(view, lparams, id)

/**
 * Provide layout from another [Hikage].
 *
 * - Note: [Hikage] view IDs will not copy to this layout
 *   when provides a complete [Hikage] instead of [Hikage.Delegate].
 *
 * ```kotlin
 * val first: Hikage = Hikageable(context) {
 *     TextView(id = "textView")
 * }
 * val second: Hikage = Hikageable(context) {
 *     TextView(id = "textView")
 *     // The view ID "textView" will not copied to this layout,
 *     // so there will be no problem of ID overlap.
 *     Layout(first)
 * }
 * ```
 * @param hikage the hikage instance.
 * @param lparams the view layout params.
 * @param id the view id, generated by default.
 * @return [Hikage]
 */
@Hikageable
fun <LP : ViewGroup.LayoutParams> Hikage.Performer<LP>.Layout(
    hikage: Hikage,
    lparams: LayoutParams? = null,
    id: String? = null
) = resolveContext().Layout(hikage, lparams, id)

/**
 * Provide layout from another [Hikage.Delegate].
 *
 * - Note: If you use [embedded], you must make sure that the introduced view IDs
 *   do not overlap with the view IDs in the current layout.
 * @param delegate the delegate instance.
 * @param lparams the view layout params.
 * @param id the view id, generated by default.
 * @param embedded whether to embed this layout (All view IDs will be copied),
 * default is true.
 * @return [Hikage]
 */
@Hikageable
fun <LP : ViewGroup.LayoutParams> Hikage.Performer<LP>.Layout(
    delegate: Hikage.Delegate<*>,
    lparams: LayoutParams? = null,
    id: String? = null,
    embedded: Boolean = true
) = resolveContext().Layout(delegate, lparams, id, embedded)

/**
 * Create a new layout params.
 *
 * Usage:
 *
 * ```kotlin
 * View(
 *     lparams = LayoutParams {
 *         // You code here.
 *     }
 * )
 * ```
 * @see ViewLayoutParams
 * @param body the layout params body.
 * @return [LayoutParams]
 */
@Hikageable
fun <LP : ViewGroup.LayoutParams> Hikage.Performer<LP>.LayoutParams(
    width: Int? = null,
    height: Int? = null,
    matchParent: Boolean = false,
    widthMatchParent: Boolean = false,
    heightMatchParent: Boolean = false,
    body: LP.() -> Unit = {}
) = resolveContext().LayoutParams(width, height, matchParent, widthMatchParent, heightMatchParent, body)

/**
 * Provide a new [View] instance [V].
 * @param factory the view factory, used to create the view instance.
 * @param lparams the view layout params.
 * @param id the view id, generated by default.
 * @param attrs the attributes body.
 * @param init the view initialization body.
 * @return [V]
 */
@Hikageable
@JvmName("ViewTyped")
inline fun <reified V : View> Hikage.Performer<*>.View(
    noinline factory: ViewConstructor<V>? = null,
    lparams: LayoutParams? = null,
    id: String? = null,
    noinline attrs: HikageAttribute = {},
    noinline init: HikageView<V> = {}
) = View(V::class, factory, lparams, id, attrs, init)

/**
 * Provide a new [ViewGroup] instance [VG].
 *
 * - Note: The [VG] must be inherited from [ViewGroup].
 * @param factory the view factory, used to create the view instance.
 * @param lparams the view layout params.
 * @param id the view id, generated by default.
 * @param attrs the attributes body.
 * @param init the view initialization body.
 * @param performer the performer body.
 * @return [VG]
 */
@Hikageable
@JvmName("ViewGroupLP")
inline fun <reified VG : ViewGroup, reified NLP : ViewGroup.LayoutParams> Hikage.Performer<*>.ViewGroup(
    noinline factory: ViewConstructor<VG>? = null,
    lparams: LayoutParams? = null,
    id: String? = null,
    noinline attrs: HikageAttribute = {},
    noinline init: HikageView<VG> = {},
    noinline performer: HikagePerformer<NLP> = {}
) = ViewGroup(VG::class, NLP::class, factory, lparams, id, attrs, init, performer)

/**
 * Provide a new [ViewGroup] instance [VG].
 *
 * - Note: The [VG] must be inherited from [ViewGroup].
 * @param factory the view factory, used to create the view instance.
 * @param lparams the view layout params.
 * @param id the view id, generated by default.
 * @param attrs the attributes body.
 * @param init the view initialization body.
 * @param performer the performer body.
 * @return [VG]
 */
@Hikageable
inline fun <reified VG : ViewGroup> Hikage.Performer<*>.ViewGroup(
    noinline factory: ViewConstructor<VG>? = null,
    lparams: LayoutParams? = null,
    id: String? = null,
    noinline attrs: HikageAttribute = {},
    noinline init: HikageView<VG> = {},
    noinline performer: HikagePerformer<ViewGroup.LayoutParams> = {}
) = ViewGroup(VG::class, factory, lparams, id, attrs, init, performer)

/**
 * Provide layout from [ViewBinding].
 * @param lparams the view layout params.
 * @param id the view id, generated by default.
 * @return [VB]
 */
@Hikageable
inline fun <reified VB : ViewBinding> Hikage.Performer<*>.Layout(
    lparams: LayoutParams? = null,
    id: String? = null
) = Layout(ViewBinding<VB>(), lparams, id)

/**
 * Provide layout from another [Hikage.Delegate].
 *
 * - Note: If you use [embedded], you must make sure that the introduced view IDs
 *   do not overlap with the view IDs in the current layout.
 * @receiver the delegate instance.
 * @param lparams the view layout params.
 * @param id the view id, generated by default.
 * @param embedded whether to embed this layout (All view IDs will be copied),
 * default is true.
 * @return [Hikage]
 */
@Hikageable
context(performer: Hikage.Performer<LP>)
operator fun <LP : ViewGroup.LayoutParams> Hikage.Delegate<*>.invoke(
    lparams: LayoutParams? = null,
    id: String? = null,
    embedded: Boolean = true
) = performer.Layout(this, lparams, id, embedded)

/**
 * Resolve the [PerformContext] from the [Hikage.Performer].
 * @receiver the performer instance.
 * @return [PerformContext]
 */
private fun <LP : ViewGroup.LayoutParams> Hikage.Performer<LP>.resolveContext() = this as? PerformContext<LP>
    ?: throw PerformerException("This Performer is not created by Hikage.")