/*
 * Hikage - A Kotlin DSL-based Android real-time UI building framework.
 * Copyright (C) 2019 HighCapable
 * https://github.com/BetterAndroid/Hikage
 *
 * Apache License Version 2.0
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * This file is created by fankes on 2026/5/31.
 */
@file:Suppress("FunctionName")

package com.highcapable.hikage.core.layout

import android.view.View
import android.view.ViewGroup
import androidx.annotation.LayoutRes
import androidx.viewbinding.ViewBinding
import com.highcapable.betterandroid.ui.extension.binding.ViewBindingBuilder
import com.highcapable.betterandroid.ui.extension.view.ViewLayoutParams
import com.highcapable.hikage.annotation.Hikageable
import com.highcapable.hikage.core.Hikage
import com.highcapable.hikage.core.attrs.HikageAttribute
import com.highcapable.hikage.core.base.HikagePerformer
import com.highcapable.hikage.core.base.HikageView
import com.highcapable.hikage.core.base.LayoutParamsBody
import com.highcapable.hikage.core.base.ViewConstructor
import kotlin.reflect.KClass

/**
 * The perform context of layout build [LP].
 */
internal interface PerformContext<LP : ViewGroup.LayoutParams> {

    /**
     * Provide a new [View] instance [V].
     * @param viewClass the view class.
     * @param factory the view factory, used to create the view instance.
     * @param lparams the view layout params.
     * @param id the view id, generated by default.
     * @param attrs the attributes body.
     * @param init the view initialization body.
     * @return [V]
     */
    @Hikageable
    fun <V : View> View(
        viewClass: KClass<V>,
        factory: ViewConstructor<V>? = null,
        lparams: LayoutParams? = null,
        id: String? = null,
        attrs: HikageAttribute = {},
        init: HikageView<V> = {}
    ): V

    /**
     * Provide a new [View] instance.
     * @param lparams the view layout params.
     * @param factory the view factory, used to create the view instance.
     * @param id the view id, generated by default.
     * @param attrs the attributes body.
     * @param init the view initialization body.
     * @return [View]
     */
    @Hikageable
    fun View(
        lparams: LayoutParams? = null,
        factory: ViewConstructor<View>? = null,
        id: String? = null,
        attrs: HikageAttribute = {},
        init: HikageView<View> = {}
    ): View

    /**
     * Provide a new [ViewGroup] instance [VG].
     *
     * Provide the new type of [ViewGroup.LayoutParams] down via [LP].
     *
     * - Note: The [VG] must be inherited from [ViewGroup].
     * @param viewClass the view class.
     * @param childLpClass the child layout params class.
     * @param factory the view factory, used to create the view instance.
     * @param lparams the view layout params.
     * @param id the view id, generated by default.
     * @param attrs the attributes body.
     * @param init the view initialization body.
     * @param performer the performer body.
     * @return [VG]
     */
    @Hikageable
    fun <VG : ViewGroup, NLP : ViewGroup.LayoutParams> ViewGroup(
        viewClass: KClass<VG>,
        childLpClass: KClass<NLP>,
        factory: ViewConstructor<VG>? = null,
        lparams: LayoutParams? = null,
        id: String? = null,
        attrs: HikageAttribute = {},
        init: HikageView<VG> = {},
        performer: HikagePerformer<NLP> = {}
    ): VG

    /**
     * Provide a new [ViewGroup] instance [VG].
     *
     * - Note: The [VG] must be inherited from [ViewGroup].
     * @param viewClass the view class.
     * @param factory the view factory, used to create the view instance.
     * @param lparams the view layout params.
     * @param id the view id, generated by default.
     * @param attrs the attributes body.
     * @param init the view initialization body.
     * @param performer the performer body.
     * @return [VG]
     */
    @Hikageable
    fun <VG : ViewGroup> ViewGroup(
        viewClass: KClass<VG>,
        factory: ViewConstructor<VG>? = null,
        lparams: LayoutParams? = null,
        id: String? = null,
        attrs: HikageAttribute = {},
        init: HikageView<VG> = {},
        performer: HikagePerformer<ViewGroup.LayoutParams> = {}
    ): VG

    /**
     * Provide layout from [resId].
     * @param resId the layout resource id.
     * @param lparams the view layout params.
     * @param id the view id, generated by default.
     * @return [View]
     */
    @Hikageable
    fun Layout(
        @LayoutRes resId: Int,
        lparams: LayoutParams?,
        id: String?
    ): View

    /**
     * Provide layout from [ViewBinding].
     * @param bindingBuilder the view binding builder.
     * @param lparams the view layout params.
     * @param id the view id, generated by default.
     * @return [VB]
     */
    @Hikageable
    fun <VB : ViewBinding> Layout(
        bindingBuilder: ViewBindingBuilder<VB>,
        lparams: LayoutParams?,
        id: String?
    ): VB

    /**
     * Provide layout from exists [View].
     * @param view the view instance.
     * @param lparams the view layout params.
     * @param id the view id, generated by default.
     * @return [View]
     */
    @Hikageable
    fun Layout(
        view: View,
        lparams: LayoutParams?,
        id: String?
    ): View

    /**
     * Provide layout from another [Hikage].
     * @param hikage the hikage instance.
     * @param lparams the view layout params.
     * @param id the view id, generated by default.
     * @return [Hikage]
     */
    @Hikageable
    fun Layout(
        hikage: Hikage,
        lparams: LayoutParams?,
        id: String?
    ): Hikage

    /**
     * Provide layout from another [Hikage.Delegate].
     * @param delegate the delegate instance.
     * @param lparams the view layout params.
     * @param id the view id, generated by default.
     * @param embedded whether to embed this layout (All view IDs will be copied).
     * @return [Hikage]
     */
    @Hikageable
    fun Layout(
        delegate: Hikage.Delegate<*>,
        lparams: LayoutParams?,
        id: String?,
        embedded: Boolean
    ): Hikage

    /**
     * Create a new layout params.
     * @see ViewLayoutParams
     * @param body the layout params body.
     * @return [LayoutParams]
     */
    fun LayoutParams(
        width: Int?,
        height: Int?,
        matchParent: Boolean,
        widthMatchParent: Boolean,
        heightMatchParent: Boolean,
        body: LayoutParamsBody<LP>
    ): LayoutParams
}