/*
 * Hikage - A real-time Android View runtime powered by Kotlin DSL.
 * Copyright (C) 2019 HighCapable
 * https://github.com/BetterAndroid/Hikage
 *
 * Apache License Version 2.0
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * This file is created by fankes on 2026/5/31.
 */
@file:Suppress("UNCHECKED_CAST")

package com.highcapable.hikage.core.layout.session

import android.content.Context
import android.util.AttributeSet
import android.view.View
import android.view.ViewGroup
import com.highcapable.hikage.core.Hikage
import com.highcapable.hikage.core.attribute.HikageAttribute
import com.highcapable.hikage.core.attribute.build
import com.highcapable.hikage.core.attribute.exception.AttributeResolvingException
import com.highcapable.hikage.core.attribute.hikageAttributeIsAvailable
import com.highcapable.hikage.core.attribute.isNotEmpty
import com.highcapable.hikage.core.attribute.widget.HikageAttributeView
import com.highcapable.hikage.core.base.HikageFactory
import com.highcapable.hikage.core.base.HikageView
import com.highcapable.hikage.core.base.ViewConstructor
import com.highcapable.hikage.core.extension.identityKey
import com.highcapable.hikage.core.layout.PerformContextImpl
import com.highcapable.hikage.core.layout.exception.PerformerException
import com.highcapable.hikage.runtime.attribute.AttributeSetResolver
import com.highcapable.kavaref.KavaRef.Companion.resolve
import com.highcapable.kavaref.extension.isNotSubclassOf
import java.io.Closeable
import java.util.concurrent.atomic.AtomicInteger
import kotlin.reflect.KClass

/**
 * The [Hikage] layout session.
 * @param factories the factories to customize the custom view in the initialization.
 */
internal class LayoutSession private constructor(private val factories: List<HikageFactory>) : Closeable {

    companion object {

        /** The view resolvers map. */
        private val viewResolvers = mutableMapOf<String?, ViewResolver<*>>()

        /** The view atomic id. */
        private val viewAtomicId = AtomicInteger(1)

        /**
         * Create a new [LayoutSession] with [factories].
         * @param factories the factories to customize the custom view in the initialization.
         * @return [LayoutSession]
         */
        fun create(factories: List<HikageFactory>) = LayoutSession(factories)
    }

    /** The performer count. */
    private var performerCount = 0

    /** The provided view count. */
    private var providedViewCount = 0

    /** The view map. */
    private val views = linkedMapOf<String, View>()

    /** The attribute set resolver map. */
    private val attributeSetResolvers = mutableMapOf<String, AttributeSetResolver>()

    /**
     * Get the [AttributeSetResolver] from [context].
     * @receiver the context.
     * @return [AttributeSetResolver] or null.
     */
    private val Context.attributeSetResolver: AttributeSetResolver? get() {
        if (!hikageAttributeIsAvailable()) return null
        return attributeSetResolvers.getOrPut(this.identityKey) { AttributeSetResolver.from(this) }
    }

    /**
     * Get the root view.
     * @return [View]
     */
    val rootView get() = views.values.firstOrNull()
        ?: throw PerformerException("No root view found, are you sure you have provided any view?")

    /**
     * Find the view.
     * @param id the view id.
     * @return [View] or null.
     */
    fun findView(id: String) = views[id]

    /**
     * Get the actual view id by [id].
     *
     * If the view with [id] is not found, it will return [View.NO_ID].
     * @param id the view id.
     * @return [Int]
     */
    fun getActualViewId(id: String) = views[id]?.id ?: View.NO_ID

    /**
     * Create a new [View] via [V].
     * @param viewClass the view class.
     * @param factory the view factory, used to create the view instance.
     * @param id the view id, generated by default.
     * @param context the context.
     * @param attrs the attributes body.
     * @param parent the parent view group.
     * @param beforeInit the view initialization body before [provideView].
     * @return [V]
     */
    fun <V : View> createView(
        viewClass: KClass<V>,
        factory: ViewConstructor<V>?,
        id: String?,
        context: Context,
        attrs: Lazy<AttributeSet>,
        parent: ViewGroup?,
        beforeInit: HikageView<V>
    ): V {
        val view = createViewFromFactory(viewClass, factory, id, context, attrs, parent)
            ?: factory?.invoke(context, attrs.value) ?: viewResolverOf(viewClass)?.build(context, attrs)
        if (view == null) throw PerformerException(
            "Create view of type ${viewClass.qualifiedName} failed. " +
                "Please make sure the view class has a constructor with Context and AttributeSet or Context."
        )

        view.beforeInit()
        provideView(view, id)
        return view
    }

    /**
     * Process with a new [AttributeSet] built from [attrs].
     * @param context the context.
     * @param attrs the attributes body.
     * @param block the block to run.
     * @return [R]
     */
    fun <R> process(context: Context, attrs: HikageAttribute, block: (Lazy<AttributeSet>, Lazy<AttributeSet>?) -> R): R {
        val resolver = context.attributeSetResolver ?: return run {
            // If user add attributes but the resolver is not available, throw an exception to avoid unexpected behavior.
            if (attrs.isNotEmpty()) throw AttributeResolvingException(
                "AttributeSetResolver is not available in this context, cannot resolve attributes. " +
                    "Please make sure you have added the `hikage-runtime-attribute` dependency for attribute resolving."
            )

            val layoutAttrs = HikageAttributeView.resolveSimpleAttributeSet(context)
            block(lazyOf(layoutAttrs), null)
        }

        val attributeItems = requireNoPerformers(Hikage.Attribute::class.qualifiedName) { attrs.build() }
        val attributeSet = lazy(LazyThreadSafetyMode.NONE) {
            resolver.newParser(attributeItems)
        }

        // Layout params attributes are not necessary for all views,
        // so we only create the layout params attribute set when there are layout params attributes.
        val lParamsItems = attributeItems.filter { it.name.startsWith("layout_") }
        val lParamsAttributeSet = lParamsItems.takeIf { it.isNotEmpty() }?.let {
            lazy(LazyThreadSafetyMode.NONE) {
                resolver.newParser(it)
            }
        }

        return try {
            block(attributeSet, lParamsAttributeSet)
        } finally {
            if (lParamsAttributeSet?.isInitialized() == true)
                resolver.release(lParamsAttributeSet.value)
            if (attributeSet.isInitialized())
                resolver.release(attributeSet.value)
        }
    }

    /**
     * Provide an exists [View].
     * @param view the view instance.
     * @param id the view id.
     * @return [String]
     */
    fun provideView(view: View, id: String?): String {
        val requireId = id ?: generateRandomViewId()
        if (views.contains(requireId)) throw PerformerException("View with id \"$requireId\" already exists.")
        if (view.id == View.NO_ID) view.id = View.generateViewId()
        views[requireId] = view
        providedViewCount++

        return requireId
    }

    /**
     * Start a new [Hikage.Performer] [LP].
     * @param lpClass the layout params type.
     * @param parent the parent view group.
     * @param attachToParent whether to attach the layout to the parent when the [parent] is filled.
     * @param context the context, priority is given to [parent]'s context.
     * @return [Hikage.Performer]
     */
    fun <LP : ViewGroup.LayoutParams> newPerformer(
        lpClass: KClass<LP>,
        parent: ViewGroup? = null,
        attachToParent: Boolean = parent != null,
        context: Context? = null
    ): Hikage.Performer<LP> = PerformContextImpl(
        session = this, 
        lpClass = lpClass,
        parent = parent,
        attachToParent = attachToParent, 
        baseContext = context
    ).apply { performerCount++ }

    /**
     * Require no [Hikage.Performer].
     * @param name the process name.
     * @param block the block.
     * @return [R]
     */
    inline fun <R> requireNoPerformers(name: String?, block: () -> R): R {
        val viewCount = providedViewCount

        val result = block()
        if (providedViewCount != viewCount) throw PerformerException(
            "Performers are not allowed to appear in ${name ?: "<unknown>"} DSL creation process."
        )

        return result
    }

    /**
     * Include a child [session].
     * @param session the child session.
     */
    fun include(session: LayoutSession) {
        val duplicateId = session.views.keys.firstOrNull { it in views }
        if (duplicateId != null) throw PerformerException(
            "Embedded layout view IDs conflict, the view id \"$duplicateId\" is already exists."
        )

        views.putAll(session.views)
        performerCount += session.performerCount
        providedViewCount += session.providedViewCount
    }

    override fun close() {
        attributeSetResolvers.forEach { (_, resolver) -> resolver.close() }
        attributeSetResolvers.clear()
    }

    /**
     * Get the view resolver for [viewClass].
     * @param viewClass the view class.
     * @return [ViewConstructor]<[V]> or null.
     */
    private fun <V : View> viewResolverOf(viewClass: KClass<V>) =
        viewResolvers[viewClass.qualifiedName] as? ViewResolver<V>? ?: run {
            var parameterCount = 0

            val resolver = viewClass.resolve().optional(silent = true)
            val constructor = resolver.firstConstructorOrNull {
                parameters(Context::class, AttributeSet::class)
            }?.apply { parameterCount = 2 } ?: resolver.firstConstructorOrNull {
                parameters(Context::class)
            }?.apply { parameterCount = 1 }

            val viewResolver = constructor?.let { ViewResolver(it, parameterCount) }
            if (viewResolver != null) viewResolvers[viewClass.qualifiedName] = viewResolver

            viewResolver
        }

    /**
     * Create a new [View] from [HikageFactory].
     * @param viewClass the view class.
     * @param factory the view factory, used to create the view instance.
     * @param id the view id.
     * @param context the context.
     * @param attrs the attribute set.
     * @param parent the parent view group.
     * @return [V] or null.
     */
    private fun <V : View> createViewFromFactory(
        viewClass: KClass<V>,
        factory: ViewConstructor<V>?,
        id: String?,
        context: Context,
        attrs: Lazy<AttributeSet>,
        parent: ViewGroup?
    ): V? {
        if (factories.isEmpty()) return null

        var processed: V? = null
        val params = HikageFactory.Params(id, attrs.value, viewClass as KClass<View>, factory)

        factories.forEach { factory ->
            val view = factory.createView(parent, processed, context, params)
            if (view != null && view::class isNotSubclassOf viewClass) throw PerformerException(
                "HikageFactory cannot cast the created view type \"${view::class}\" to \"${viewClass.qualifiedName ?: "<unknown>"}\", " +
                    "please confirm that the view type you created is correct."
            )

            if (view != null) processed = view as? V?
        }

        return processed
    }

    /**
     * Generate random view id.
     * @return [String]
     */
    private fun generateRandomViewId() = "anonymous@${viewAtomicId.getAndIncrement().toString().padStart(4, '0')}"
}