/*
 * Hikage - An Android responsive UI building tool.
 * Copyright (C) 2019 HighCapable
 * https://github.com/BetterAndroid/Hikage
 *
 * Apache License Version 2.0
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * This file is created by fankes on 2026/5/31.
 */
@file:Suppress("UNCHECKED_CAST")

package com.highcapable.hikage.core.layout.session

import android.content.Context
import android.content.res.XmlResourceParser
import android.util.AttributeSet
import android.view.View
import android.view.ViewGroup
import com.highcapable.hikage.core.Hikage
import com.highcapable.hikage.core.attrs.HikageAttribute
import com.highcapable.hikage.core.attrs.build
import com.highcapable.hikage.core.attrs.entity.AttributeItem
import com.highcapable.hikage.core.attrs.runtime.resolver.AttributeSetResolver
import com.highcapable.hikage.core.base.HikageFactory
import com.highcapable.hikage.core.base.PerformerException
import com.highcapable.hikage.core.layout.PerformContextImpl
import com.highcapable.kavaref.KavaRef.Companion.resolve
import com.highcapable.kavaref.extension.isNotSubclassOf
import java.util.concurrent.atomic.AtomicInteger
import kotlin.reflect.KClass

/**
 * The [Hikage] layout session.
 * @param factories the factories to customize the custom view in the initialization.
 */
internal class LayoutSession private constructor(private val factories: List<HikageFactory>) {

    companion object {

        /** The view constructors map. */
        private val viewConstructors = mutableMapOf<String?, ViewConstructor<*>>()

        /** The view atomic id. */
        private val viewAtomicId = AtomicInteger(0x7F00000)

        /**
         * Create a new [LayoutSession] with [factories].
         * @param factories the factories to customize the custom view in the initialization.
         * @return [LayoutSession]
         */
        fun create(factories: List<HikageFactory>) = LayoutSession(factories)
    }

    /** The performer count. */
    private var performerCount = 0

    /** The provided view count. */
    private var providedViewCount = 0

    /** The view map. */
    private val views = linkedMapOf<String, View>()

    /** The view id map. */
    private val viewIds = mutableMapOf<String, Int>()

    /**
     * Get the root view.
     * @return [View]
     */
    val rootView get() = views.values.firstOrNull()
        ?: throw PerformerException("No root view found, are you sure you have provided any view?")

    /**
     * Find the view.
     * @param id the view id.
     * @return [View] or null.
     */
    fun findView(id: String) = views[id]

    /**
     * Get the actual view id by [id].
     * @param id the view id.
     * @return [Int] or -1.
     */
    fun getActualViewId(id: String) = viewIds[id] ?: -1

    /**
     * Provide the parent [ViewGroup] as the root view.
     * @param parent the parent view group.
     */
    fun provideParent(parent: ViewGroup) = provideView(parent, generateRandomViewId())

    /**
     * Create a new [View] via [V].
     * @param viewClass the view class.
     * @param id the view id, generated by default.
     * @param context the context.
     * @param attrs the attributes body.
     * @param parent the parent view group.
     * @return [V]
     */
    fun <V : View> createView(viewClass: KClass<V>, id: String?, context: Context, attrs: Lazy<AttributeSet>, parent: ViewGroup?): V {
        val view = createViewFromFactory(viewClass, id, context, attrs, parent)
            ?: getViewConstructor(viewClass)?.build(context, attrs)
        if (view == null) throw PerformerException(
            "Create view of type ${viewClass.qualifiedName} failed. " +
                "Please make sure the view class has a constructor with Context and AttributeSet or Context."
        )

        provideView(view, id)
        return view
    }

    /**
     * Process with a new [AttributeSet] built from [attrs].
     * @param context the context.
     * @param attrs the attributes body.
     * @param block the block to run.
     * @return [R]
     */
    fun <R> process(context: Context, attrs: HikageAttribute, block: (Lazy<AttributeSet>) -> R): R {
        val resolver = AttributeSetResolver.from(context)
        val attributeSet = lazy(LazyThreadSafetyMode.NONE) { resolver.newAttributeSet(context, attrs.build()) }

        return try {
            block(attributeSet)
        } finally {
            if (attributeSet.isInitialized())
                (attributeSet.value as? XmlResourceParser)?.let { resolver.release(it) }
        }
    }

    /**
     * Provide an exists [View].
     * @param view the view instance.
     * @param id the view id.
     * @return [String]
     */
    fun provideView(view: View, id: String?): String {
        val (requireId, viewId) = generateViewId(id)
        view.id = viewId
        views[requireId] = view
        providedViewCount++

        return requireId
    }

    /**
     * Start a new [Hikage.Performer] [LP].
     * @param lpClass the layout params type.
     * @param parent the parent view group.
     * @param attachToParent whether to attach the layout to the parent when the [parent] is filled.
     * @param context the context, priority is given to [parent]'s context.
     * @return [Hikage.Performer]
     */
    fun <LP : ViewGroup.LayoutParams> newPerformer(
        lpClass: KClass<LP>,
        parent: ViewGroup? = null,
        attachToParent: Boolean = parent != null,
        context: Context? = null
    ): Hikage.Performer<LP> = PerformContextImpl(
        session = this, 
        lpClass = lpClass,
        parent = parent,
        attachToParent = attachToParent, 
        baseContext = context
    ).apply { performerCount++ }

    /**
     * Require no [Hikage.Performer].
     * @param name the process name.
     * @param block the block.
     */
    inline fun requireNoPerformers(name: String?, block: () -> Unit) {
        val viewCount = providedViewCount

        block()
        if (providedViewCount != viewCount) throw PerformerException(
            "Performers are not allowed to appear in ${name ?: "<unknown>"} DSL creation process."
        )
    }

    /**
     * Include a delegate.
     * @param delegate the delegate.
     * @param context the context.
     * @param embedded the embedded flag.
     * @return [Hikage]
     */
    fun include(delegate: Hikage.Delegate<*>, context: Context, embedded: Boolean): Hikage {
        val hikage = delegate.create(context)
        if (!embedded) return hikage

        val session = hikage.session
        val duplicateId = session.viewIds.keys.firstOrNull { it in viewIds }
        if (duplicateId != null) throw PerformerException(
            "Embedded layout view IDs conflict, the view id \"$duplicateId\" is already exists."
        )

        viewIds.putAll(session.viewIds)
        views.putAll(session.views)
        performerCount += session.performerCount
        providedViewCount += session.providedViewCount

        return hikage
    }

    /**
     * Get the view constructor.
     * @param viewClass the view class.
     * @return [ViewConstructor]<[V]> or null.
     */
    private fun <V : View> getViewConstructor(viewClass: KClass<V>) =
        viewConstructors[viewClass.qualifiedName] as? ViewConstructor<V>? ?: run {
            var parameterCount = 0

            val resolver = viewClass.resolve().optional(silent = true)
            val constructor = resolver.firstConstructorOrNull {
                parameters(Context::class, AttributeSet::class)
            }?.apply { parameterCount = 2 } ?: resolver.firstConstructorOrNull {
                parameters(Context::class)
            }?.apply { parameterCount = 1 }

            val viewConstructor = constructor?.let { ViewConstructor(it, parameterCount) }
            if (viewConstructor != null) viewConstructors[viewClass.qualifiedName] = viewConstructor

            viewConstructor
        }

    /**
     * Create a new [View] from [HikageFactory].
     * @param viewClass the view class.
     * @param id the view id.
     * @param context the context.
     * @param attrs the attribute set.
     * @param parent the parent view group.
     * @return [V] or null.
     */
    private fun <V : View> createViewFromFactory(
        viewClass: KClass<V>,
        id: String?,
        context: Context,
        attrs: Lazy<AttributeSet>,
        parent: ViewGroup?
    ): V? {
        if (factories.isEmpty()) return null

        var processed: V? = null
        val params = HikageFactory.Params(id, attrs.value, viewClass as KClass<View>)

        factories.forEach { factory ->
            val view = factory.createView(parent, processed, context, params)
            if (view != null && view::class isNotSubclassOf viewClass) throw PerformerException(
                "HikageFactory cannot cast the created view type \"${view::class}\" to \"${viewClass.qualifiedName ?: "<unknown>"}\", " +
                    "please confirm that the view type you created is correct."
            )

            if (view != null) processed = view as? V?
        }

        return processed
    }

    /**
     * Generate view id from [id].
     * @param id the view id.
     * @return [Pair]<[String], [Int]>
     */
    private fun generateViewId(id: String?): Pair<String, Int> {
        /**
         * Generate a new view id.
         * @param id the view id.
         * @return [Int]
         */
        fun doGenerate(id: String): Int {
            val generateId = View.generateViewId()

            if (viewIds.contains(id)) throw PerformerException("View with id \"$id\" already exists.")
            viewIds[id] = generateId

            return generateId
        }

        val requireId = id ?: generateRandomViewId()
        val viewId = doGenerate(requireId)

        return requireId to viewId
    }

    /**
     * Generate random view id.
     * @return [String]
     */
    private fun generateRandomViewId() = "anonymous@${viewAtomicId.getAndIncrement().toHexString()}"

    /**
     * Create a new [AttributeSet] from [AttributeItem].
     * @receiver the attribute set resolver.
     * @param context the context.
     * @param attrs the injected attributes.
     * @return [AttributeSet]
     */
    private fun AttributeSetResolver.newAttributeSet(
        context: Context,
        attrs: List<AttributeItem>
    ): AttributeSet = newParser(context, attrs)
}